/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../../pages/__root'
import { Route as SelectTeamImport } from './../../pages/select-team'
import { Route as IndexImport } from './../../pages/index'

// Create/Update Routes

const SelectTeamRoute = SelectTeamImport.update({
  id: '/select-team',
  path: '/select-team',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/select-team': {
      id: '/select-team'
      path: '/select-team'
      fullPath: '/select-team'
      preLoaderRoute: typeof SelectTeamImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-team': typeof SelectTeamRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-team': typeof SelectTeamRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/select-team': typeof SelectTeamRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/select-team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/select-team'
  id: '__root__' | '/' | '/select-team'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectTeamRoute: typeof SelectTeamRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectTeamRoute: SelectTeamRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/select-team"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/select-team": {
      "filePath": "select-team.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
